### ISSUE TITLE
 no dispatch function defined for #\{

### ISSUE THREAD

**Issue by francogrex** [y2q-actionman/with-c-syntax#1]
It's a nice package but some bugs must be resolved for example in sbcl:
(with-c-syntax ()
# {

  format (t, "Hello World!");
}#)

debugger invoked on a SB-INT:SIMPLE-READER-ERROR in thread
# <THREAD "main thread" RUNNING {240FE8C1}>:

no dispatch function defined for #{
File-Position: 103
Stream: #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {22402939}>

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(SB-INT:SIMPLE-READER-ERROR #<SYNONYM-STREAM :SYMBOL SB-SYS:*STDIN* {22402939}> "no dispatch function defined for ~S" #{)
0]

**Comment by y2q-actionman** [comment]
Thank You.
I notice I forgot to enable reader-macros on the examples in README.
fixed in 86b4aba1cd080dd575d126b7013d2312c2d1e954

**Comment by francogrex** [comment]
Thanks. This package is awesome really good work.
