### ISSUE TITLE
Some systems failed to build for Quicklisp dist

### ISSUE THREAD

**Issue by quicklisp** [y2q-actionman/with-c-syntax#15]
Building with SBCL 2.0.5 / ASDF 3.3.1 for quicklisp dist creation.

Trying to build commit id b42241d3950582c6a690655af1612e364b2b99da

*with-c-syntax-test* fails to build with the following error:

```
Unhandled FLOATING-POINT-INVALID-OPERATION in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A18083}>: arithmetic error FLOATING-POINT-INVALID-OPERATION signalled

```

*with-c-syntax* fails to build with the following error:

```
Unhandled FLOATING-POINT-INVALID-OPERATION in thread #<SB-THREAD:THREAD "main thread" RUNNING {1000A18083}>: arithmetic error FLOATING-POINT-INVALID-OPERATION signalled

```

[Full log here](http://report.quicklisp.org/2021-06-22/failure-report/with-c-syntax.html)

**Comment by y2q-actionman** [comment]
Confirming..

**Comment by y2q-actionman** [comment]
Passed
* SBCL 2.1.5 on MacOS X Big Sur
* Allegro CL 10.1 on  on MacOS X Big Sur

**Comment by y2q-actionman** [comment]
I think this is a bug of SBCL 2.0.5.

SBCL 2.0.5 cannot compile a code includes NaN in its body. This function raises an error on compiling:

```lisp
(defun return-nan ()
  float-features:double-float-nan)
```

I added a workaround on commit 32c8c608f01a43df190c3eb2107a772817173030 .
See comments in this commit.
