### ISSUE TITLE
Special-casing macros with `&BODY`

### ISSUE THREAD

**Issue by phoe** [y2q-actionman/with-c-syntax#4]
The README mentions:

https://github.com/y2q-actionman/with-c-syntax/blob/e3e9ae2f1f29115f30141e3ada33372e2ce6b65d/test/libc_string.lisp#L143-L144

I think it should be possible to specify either manual or semi-automatic translations for macros which have a `&BODY` parameter, such as `WITH-OPEN-FILE`. A `&BODY` parameter is equivalent to a logical block that could be enclosed within a C-style block.

For example, the above macro could be written as:

```c
output = with-output-to-string(*standard-output*) {
    format(t, "Found '~C' starting at '~A'", target, result));
  };
```

**Comment by y2q-actionman** [comment]
It looks interesting. I remind `with` syntax of JavaScript. However I take a time to implement it, because I found a bug in compound form processing...

**Comment by y2q-actionman** [comment]
Sorry for the late reply. (three years..)
I finally implemented a new syntax for doing this.

See examples in README:
https://github.com/y2q-actionman/with-c-syntax#support-with--like-macros

**Comment by phoe** [comment]
Thank you!
